In [3]:
#1. Import the NUMPY package under the name np.
# [your code here]

import numpy as np

In [4]:
#2. Print the NUMPY version and the configuration.
# [your code here]

print(np.show_config())

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/MIQUEL/anaconda3/envs/Original/Library/include
    lib directory: C:/Users/MIQUEL/anaconda3/envs/Original/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    sys

In [5]:
!pip show numpy

Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYR

In [6]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
# [your code here]

a = np.random.random(size=(2, 3, 5))

In [7]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
     

In [8]:
help(np.random.poisson)

Help on built-in function poisson:

poisson(...) method of numpy.random.mtrand.RandomState instance
    poisson(lam=1.0, size=None)

    Draw samples from a Poisson distribution.

    The Poisson distribution is the limit of the binomial distribution
    for large N.

    .. note::
        New code should use the `~numpy.random.Generator.poisson`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    lam : float or array_like of floats
        Expected number of events occurring in a fixed-time interval,
        must be >= 0. A sequence must be broadcastable over the requested
        size.
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  If size is ``None`` (default),
        a single value is returned if ``lam`` is a scalar. Otherwise,
        ``np.array(lam).size`` samples are drawn.



In [9]:
help(np.random.laplace)

Help on built-in function laplace:

laplace(...) method of numpy.random.mtrand.RandomState instance
    laplace(loc=0.0, scale=1.0, size=None)

    Draw samples from the Laplace or double exponential distribution with
    specified location (or mean) and scale (decay).

    The Laplace distribution is similar to the Gaussian/normal distribution,
    but is sharper at the peak and has fatter tails. It represents the
    difference between two independent, identically distributed exponential
    random variables.

    .. note::
        New code should use the `~numpy.random.Generator.laplace`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    loc : float or array_like of floats, optional
        The position, :math:`\mu`, of the distribution peak. Default is 0.
    scale : float or array_like of floats, optional
        :math:`\lambda`, the exponential decay. Default is 1. Must be non-
     

In [5]:
#4. Print a.
# [your code here]

print(a)

[[[0.10794192 0.98799941 0.22960563 0.44262893 0.3426828 ]
  [0.65167065 0.88204688 0.69653149 0.06471186 0.16432261]
  [0.95889664 0.76836532 0.39490811 0.0625627  0.25577572]]

 [[0.30732323 0.428793   0.67479885 0.6685034  0.72959244]
  [0.14512295 0.84866917 0.44443184 0.28649924 0.21396912]
  [0.7217587  0.3421529  0.86026719 0.76230837 0.77212707]]]


In [12]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
# Assign the array to variable "b"
# [your code here]

b = np.ones((5, 3, 2))

# Shouldn't it be 5x3x2 instead of 5x2x3? If not, point 10. doesn't work!

In [13]:
#6. Print b.
# [your code here]

print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [15]:
#7. Do a and b have the same size? How do you prove that in Python code?
# [your code here]

print(a.size)     # Option 1
print(b.size)

if a.size == b.size:     # Option 2
    print("Both arrays a and b have the same size!")
else:
    print("Arrays a and b have different size!")

a.size == b.size     # Option 3

30
30
Both arrays a and b have the same size!


True

In [17]:
#8. Are you able to add a and b? Why or why not?
# [your code here]

    # It's not possible to add a and b (element wise computation) because they have different shapes:

print(a.shape)
print(b.shape)

arrays_addition = a + b
arrays_addition

(2, 3, 5)
(5, 3, 2)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

In [18]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
# [your code here]

c = np.transpose(b)
print(c)
print(c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


In [20]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
# [your code here]

d = a + c

# Another option: d = np.add (a, c)

In [21]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
# [your code here]

print(a)
print(d)

# The result of array 'd' is equal to array 'a' plus 1, wich are the values of array 'c'. 
# The addition has been possible because of the transposal of array 'b' in order to get the same shape/structure of array 'a'.
# In order to be able to sum to arrays, they must have the same shape since the math operator 'sum' is applied 'position by position'.
# Thus, if arrays don't have same shape/structure, math operators fail.

[[[0.02221159 0.33679989 0.6060103  0.05032252 0.58647159]
  [0.42048661 0.6198048  0.15104912 0.93807175 0.1432553 ]
  [0.85177159 0.97934321 0.13204549 0.64686288 0.8835047 ]]

 [[0.75126372 0.9230741  0.87407966 0.41853541 0.7481671 ]
  [0.5547772  0.00123725 0.8351933  0.01389981 0.60554797]
  [0.90885124 0.12903494 0.51504435 0.71330476 0.77376381]]]
[[[1.02221159 1.33679989 1.6060103  1.05032252 1.58647159]
  [1.42048661 1.6198048  1.15104912 1.93807175 1.1432553 ]
  [1.85177159 1.97934321 1.13204549 1.64686288 1.8835047 ]]

 [[1.75126372 1.9230741  1.87407966 1.41853541 1.7481671 ]
  [1.5547772  1.00123725 1.8351933  1.01389981 1.60554797]
  [1.90885124 1.12903494 1.51504435 1.71330476 1.77376381]]]


In [22]:
#12. Multiply a and c. Assign the result to e.
# [your code here]

e = a * c

In [23]:
#13. Does e equal to a? Why or why not?
# [your code here]

print(a)
print(e)

if e.all() == a.all():
    print("Both arrays are equal!")
else:
    print("Arrays are different!")

# Both arrays are equal because values of array 'a' are multiplied by values of array 'c' (which are all equal to 1), 'position by position'.

[[[0.02221159 0.33679989 0.6060103  0.05032252 0.58647159]
  [0.42048661 0.6198048  0.15104912 0.93807175 0.1432553 ]
  [0.85177159 0.97934321 0.13204549 0.64686288 0.8835047 ]]

 [[0.75126372 0.9230741  0.87407966 0.41853541 0.7481671 ]
  [0.5547772  0.00123725 0.8351933  0.01389981 0.60554797]
  [0.90885124 0.12903494 0.51504435 0.71330476 0.77376381]]]
[[[0.02221159 0.33679989 0.6060103  0.05032252 0.58647159]
  [0.42048661 0.6198048  0.15104912 0.93807175 0.1432553 ]
  [0.85177159 0.97934321 0.13204549 0.64686288 0.8835047 ]]

 [[0.75126372 0.9230741  0.87407966 0.41853541 0.7481671 ]
  [0.5547772  0.00123725 0.8351933  0.01389981 0.60554797]
  [0.90885124 0.12903494 0.51504435 0.71330476 0.77376381]]]
Both arrays are equal!


In [25]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
# [your code here]

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.979343210868274
1.0012372545038466
1.5377928659732938


In [26]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
# [your code here]

f = np.empty((2, 3, 5))
print(f)

[[[0.02221159 0.33679989 0.6060103  0.05032252 0.58647159]
  [0.42048661 0.6198048  0.15104912 0.93807175 0.1432553 ]
  [0.85177159 0.97934321 0.13204549 0.64686288 0.8835047 ]]

 [[0.75126372 0.9230741  0.87407966 0.41853541 0.7481671 ]
  [0.5547772  0.00123725 0.8351933  0.01389981 0.60554797]
  [0.90885124 0.12903494 0.51504435 0.71330476 0.77376381]]]


In [27]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
# [your code here]

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100

In [28]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
# [your code here]

print(d)
print(f)

[[[1.02221159 1.33679989 1.6060103  1.05032252 1.58647159]
  [1.42048661 1.6198048  1.15104912 1.93807175 1.1432553 ]
  [1.85177159 1.97934321 1.13204549 1.64686288 1.8835047 ]]

 [[1.75126372 1.9230741  1.87407966 1.41853541 1.7481671 ]
  [1.5547772  1.00123725 1.8351933  1.01389981 1.60554797]
  [1.90885124 1.12903494 1.51504435 1.71330476 1.77376381]]]
[[[ 25.  25.  75.  25.  75.]
  [ 25.  75.  25.  75.  25.]
  [ 75. 100.  25.  75.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 75.   0.  75.  25.  75.]
  [ 75.  25.  25.  75.  75.]]]


In [29]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""
# [your code here]

f = np.empty((2, 3, 5), dtype=str)     # Another option: h = f.astype(str)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = "D"
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = "B"
            elif d[i, j, k] == d_mean:
                f[i, j, k] = "C"
            elif d[i, j, k] == d_min:
                f[i, j, k] = "E"
            elif d[i, j, k] == d_max:
                f[i, j, k] = "A"

print(f)

[[['D' 'D' 'B' 'D' 'B']
  ['D' 'B' 'D' 'B' 'D']
  ['B' 'A' 'D' 'B' 'B']]

 [['B' 'B' 'B' 'D' 'B']
  ['B' 'E' 'B' 'D' 'B']
  ['B' 'D' 'D' 'B' 'B']]]


In [30]:
help(np.quantile)

Help on _ArrayFunctionDispatcher in module numpy:

quantile(a, q, axis=None, out=None, overwrite_input=False, method='linear', keepdims=False, *, interpolation=None)
    Compute the q-th quantile of the data along the specified axis.

    .. versionadded:: 1.15.0

    Parameters
    ----------
    a : array_like of real numbers
        Input array or object that can be converted to an array.
    q : array_like of float
        Probability or sequence of probabilities for the quantiles to compute.
        Values must be between 0 and 1 inclusive.
    axis : {int, tuple of int, None}, optional
        Axis or axes along which the quantiles are computed. The default is
        to compute the quantile(s) along a flattened version of the array.
    out : ndarray, optional
        Alternative output array in which to place the result. It must have
        the same shape and buffer length as the expected output, but the
        type (of the output) will be cast if necessary.
    overwrite_inp